// <auto-generated />
using System;
using Backend.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(RegistroAccesoContext))]
    partial class RegistroAccesoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Service.Models.Alumno", b =>
                {
                    b.Property<int>("IdAlumno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAlumno"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoAlumno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("IdAlumno");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            IdAlumno = 1,
                            Apellido = "Pérez",
                            Dni = "12345678",
                            EstadoAlumno = "Activo",
                            Nombre = "Juan"
                        },
                        new
                        {
                            IdAlumno = 2,
                            Apellido = "García",
                            Dni = "87654321",
                            EstadoAlumno = "Egresado",
                            Nombre = "Ana"
                        },
                        new
                        {
                            IdAlumno = 3,
                            Apellido = "Martínez",
                            Dni = "11223344",
                            EstadoAlumno = "Suspendido",
                            Nombre = "Luis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
